apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-piolt-deployment
  labels:
    app: eks-piolt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-piolt
  template:
    metadata:
      labels:
        app: eks-piolt
    spec:
      containers:
        - name: eks-piolt-container
          #image: 452295101062.dkr.ecr.me-south-1.amazonaws.com/eks-piolt-ecr:latest
          image: 452295101062.dkr.ecr.me-south-1.amazonaws.com/eks-piolt-ecr:${{ secrets.IMAGE_TAG }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
