apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-piolt-deployment
  labels:
    app: eks-piolt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-piolt
  template:
    metadata:
      labels:
        app: eks-piolt
    spec:
      containers:
        - name: eks-piolt-ecr
          #image: 452295101062.dkr.ecr.me-south-1.amazonaws.com/eks-piolt-ecr:latest
          #image: 452295101062.dkr.ecr.me-south-1.amazonaws.com/eks-piolt-ecr:${{secrets.IMAGETAG_K8s}}
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
    strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
